services:
  app:
    build: .
    container_name: pastebin
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - minio
    networks:
      - pastebin_network
    env_file:
      - .env

  postgres:
    image: postgres:latest
    container_name: postgresPastebin
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - pastebin_network
    volumes:
      - ./src/databases/database.sql:/docker-entrypoint-initdb.d/database.sql
      - postgres_data:/data/db

  redis:
    image: redis:latest
    container_name: redisPastebin
    ports:
      - "6379:6379"
    networks:
      - pastebin_network

  minio:
    image: minio/minio:latest
    container_name: minioPastebin
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    networks:
      - pastebin_network
    volumes:
      - minio_data:/data
    command: server /data

networks:
  pastebin_network:
    driver: bridge

volumes:
  postgres_data: {}
  minio_data: {}
